name: Check

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  run-checks:
    name: ${{ matrix.os }}
    timeout-minutes: 5

    strategy:
      matrix:
        os:
          - "ubuntu-latest"

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: 22

      - name: Check non-Python formatting
        run: |
          npx prettier --check src/newsyacht/web/static

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6

      - name: Lint Python
        run: |
          uv run -- ruff check

      - name: Check Python formatting
        run: |
          uv run -- ruff format --check

      - name: Check types
        run: |
          uv run -- ty check

      - name: Check packaging
        run: |
          uv lock --check
